import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "@radix-ui/themes";
import "@/app/styles/global.scss";
import Header from "../components/Header";
import NextAuthProvider from "@/app/_auth";
import styles from "./layout.module.scss";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.className}>
        <NextAuthProvider>
          <Header />
          <main className={styles.main}>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
